'''
Created on Jul 30, 2017

@author: Aditya

This program demonstrates the exception handling in python code.
'''

def main(): pass

if __name__ == '__main__':main()